apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "web-app"
  name: "iri-generator-service"
  labels:
    app: "iri-generator-service"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "iri-generator-service-${env}"
      namespace: "metadata-mgm"
      labels:
        app: "iri-generator-service"
        app.kubernetes.io/component: "iri-generator-service-${env}"
        app.kubernetes.io/instance: "iri-generator-service-${env}"
        app.kubernetes.io/name: "iri-generator-service"
        app.kubernetes.io/part-of: "iri-generator-service"
        app.openshift.io/runtime: "iri-generator-service"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "iri-generator-service"
        env: ${env}
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
      name: "iri-generator-service-${env}"
      namespace: "metadata-mgm"
      labels:
        app: "iri-generator-service"
        app.kubernetes.io/component: "iri-generator-service-${env}"
        app.kubernetes.io/instance: "iri-generator-service-${env}"
        app.kubernetes.io/name: "iri-generator-service"
        app.kubernetes.io/part-of: "iri-generator-service"
        app.openshift.io/runtime: "iri-generator-service"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "iri-generator-service"
          env: ${env}
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "iri-generator-service"
            deploymentconfig: "iri-generator-service-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "iri-generator-service-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health/live
                  port: ${{svc_port}}
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              readinessProbe:
                tcpSocket:
                  port: ${{svc_port}}
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "iri-generator-service-${env}"
                - secretRef:
                    name: "iri-generator-service-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/metadata-mgm/iri-generator-service:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "iri-generator-service-${env}"
      namespace: "metadata-mgm"
      labels:
        app: "iri-generator-service"
        app.kubernetes.io/component: "iri-generator-service-${env}"
        app.kubernetes.io/instance: "iri-generator-service-${env}"
        app.kubernetes.io/name: "iri-generator-service"
        app.kubernetes.io/part-of: "iri-generator-service"
        app.openshift.io/runtime: "iri-generator-service"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      POSTGRES_USER: some_value
      POSTGRES_HOST: some_value
      POSTGRES_DB: some_value
      POSTGRES_PORT: some_value
      POSTGRES_ECHO: some_value
      POSTGRES_POOL_SIZE: some_value
  - kind: Secret
    apiVersion: v1
    metadata:
      name: "iri-generator-service-${env}"
      namespace: "metadata-mgm"
      labels:
        app: "iri-generator-service"
        app.kubernetes.io/component: "iri-generator-service-${env}"
        app.kubernetes.io/instance: "iri-generator-service-${env}"
        app.kubernetes.io/name: "iri-generator-service"
        app.kubernetes.io/part-of: "iri-generator-service"
        app.openshift.io/runtime: "iri-generator-service"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    stringData:
      POSTGRES_PASSWORD: ''
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "328"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"